version: "3.8"

services:
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    volumes:
      - ../calibre/config:/config
      - /volume2/media/books:/books
      - /volume2/media/books-dump:/books-dump
      - /volume2/media/books-staging:/books-staging
      - /volume1/docker/calibre/scripts:/scripts
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 8082:8080 #Calibre main GUI
      - 8083:8181 # Calibre-web
      - 8081:8081  # Calibre Content Server
    networks:
      - tds_net
    restart: unless-stopped

  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    depends_on:
      - calibre
    volumes:
      - /volume2/media/books:/books
      - ../calibre-web/config:/config
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS=linuxserver/calibre-web:calibre
    ports:
      - 8084:8083
    networks:
      - tds_net
    restart: unless-stopped

  readarr:
    image: hotio/readarr:nightly
    container_name: readarr
    hostname: readarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /volume1/docker/readarr/config:/config
      - /volume1/docker/nzbget/downloads:/downloads
      - /volume1/docker/calibre/scripts:/scripts
      - /volume2/media/books:/books
      - /volume2/media/books-dump:/books-dump
      - /volume2/media/books-staging:/books-staging
    ports:
      - "8787:8787"
    networks:
      - tds_net
    restart: unless-stopped

networks:
  tds_net:
    external: true
