version: "3.8"

services:
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    volumes:
      - ../calibre/config:/config
      - /volume2/plex-media/calibre-library:/books
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 8082:8080
      - 8083:8181
    restart: unless-stopped

  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    depends_on:
      - calibre
    volumes:
      - /volume2/plex-media/calibre-library:/books
      - ../calibre-web/config:/config
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS=linuxserver/calibre-web:calibre
    ports:
      - 8084:8083
    restart: unless-stopped
