version: "3.9"

services:
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    environment:
      - TZ=${TZ}
    volumes:
      - /volume1/docker/influxdb/data:/var/lib/influxdb2
      - /volume1/docker/influxdb/config:/etc/influxdb2
    ports:
      - "8086:8086"
    networks:
      - monitoring_net
    restart: unless-stopped

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    environment:
      - TZ=${TZ}
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - /volume1/docker/grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring_net
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - /volume1/docker/prometheus/config:/etc/prometheus
      - /volume1/docker/prometheus/data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - monitoring_net
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel run
    volumes:
      - /volume1/docker/cloudflared:/etc/cloudflared
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    restart: unless-stopped
    networks:
      - monitoring_net

networks:
  monitoring_net:
    external: true